### ISSUE TITLE
Abstract in Finnish and in English

### ISSUE THREAD

**Issue by looppi** [datakurre/tutkielma#1]
Currently it is required that the thesis has abstract both in Finnish and in English. The current implementation allows the abstract only in Finnish.

**Comment by looppi** [comment]
This actually goes deeper than that. On the abstract page also the university name should be in English, which complicates things a bit. Found at least a partial solution to this by defining command which allows setting some constants in multilingual manner.

First redefine command for localization:
```
\newcommand{\newlocalizedconstant}[3]{%
	\newcommand{#1}{%
		\iflanguage{finnish}{#2}{%
		\iflanguage{english}{#3}{}%
		}%
	}%
}
```

Then define few constants localized
```
\newlocalizedconstant{\myabstractname}{Tiivistelm\"a}{Abstract}
\newlocalizedconstant{\mykeywordsname}{Avainsanat}{Keywords}
```
And print them where necessary.

The bad side is that at least I don't know how to play with those defined values like type and university in this manner and it will mess up the template if I change them to commands everywhere.

**Comment by datakurre** [comment]
@looppi Wouldn't this be looks too smart? I'd avoid trying to make this generic, but rather just add new \abstract2-command with new \variable2-style variables.

**Comment by looppi** [comment]
That is true, the code just looked too ugly to touch at first glance, I'll create pull request with the foreign abstract later.

**Comment by datakurre** [comment]
It's just LaTeX, but yes, making it generic multilingual would make it really ugly. That said, the foreign abstract could be wrapped into english language environment, which would make it e.g. hyphenate correctly. But I can add that later.
