### ISSUE TITLE
Contents section spacings

### ISSUE THREAD

**Issue by looppi** [datakurre/tutkielma#3]
Currently spacing in the contents section is not optimal and this was brought when I presented a thesis based on this template.

![selection_051](https://cloud.githubusercontent.com/assets/5002215/6199676/6da13caa-b45b-11e4-8997-0bf11d08d311.png)

Additionally I noticed following problems in the contens listing: abstract sections are not shown on contents and there's no spacing before the first real chapter entry.

### Correct:
![selection_052](https://cloud.githubusercontent.com/assets/5002215/6199730/142be9c4-b45e-11e4-9d78-c4c0cc35ec88.png)

### Current:
![selection_053](https://cloud.githubusercontent.com/assets/5002215/6199731/19d24990-b45e-11e4-916f-0f11bc378440.png)

### Needed changes
- [ ] Vertical spacing between "pre content" entries (sisällyt, kuviot and taulukot) should be the same as with first level content headings
- [ ] Vertical spacing on sections, because section with number greater than 10 is too close to the section title entry

**Comment by datakurre** [comment]
Ommm... Could you make a [  ] checkbox list of these issue? Abstracts were hidden by purpose, som there are changes in instructions :)

How should "optimal" spacing look like?

**Comment by datakurre** [comment]
Vertical spacing issues should be trivial. Horizontal is not, because there is only a fixed value fo that.

**Comment by looppi** [comment]
[] Vertical spacing between "pre content" entries (sisällyt, kuviot and taulukot) should be the same as with first level content headings
[] Vertical spacing on sections, because section with number greater than 10 is too close to the section title entry

**Comment by datakurre** [comment]
Working on this.

**Comment by datakurre** [comment]
Almost there...

![nayttokuva 2015-05-14 kello 3 17 40](https://cloud.githubusercontent.com/assets/160447/7623803/d3732d14-f9e7-11e4-909d-3f9431dd3da6.png)

**Comment by datakurre** [comment]
@looppi Just checking. Is this the correct guide? https://www.jyu.fi/it/opiskelu-ohjeet/TKTL-ohjeet/opinnaytetyot/ohjeita-tutkielmien-tekijoille/Raportointiohje_2013.pdf

Now just need to get dottetlines away before the first numbered chapter.

**Comment by looppi** [comment]
I would say that the dottedlines should not be removed from the pre-content toc entries. I'll check from other source.

**Comment by datakurre** [comment]
Done?

![nayttokuva 2015-05-14 kello 13 40 34](https://cloud.githubusercontent.com/assets/160447/7630461/dfba6e32-fa3e-11e4-8248-2cf2707d2822.png)

**Comment by looppi** [comment]
Looks awesome! Thanks a million!
