### ISSUE TITLE
Bibliography to match current specifications

### ISSUE THREAD

**Issue by looppi** [datakurre/tutkielma#4]
The current specification is found here: https://www.jyu.fi/it/opiskelu-ohjeet/TKTL-ohjeet/opinnaytetyot/ohjeita-tutkielmien-tekijoille/Raportointiohje_2013.pdf

The version used in this template uses partly old formatting which has for example unnecessary urls in them.

**Comment by datakurre** [comment]
Any chance that you could enumerate the difference (well, changes since 2007 :)

**Comment by looppi** [comment]
I'll create a pull request later, this was created actually for me. :)

**Comment by datakurre** [comment]
- [ ] I know the checkbox syntax in GH issues and how it could help me to tracking sub-issues :)

**Comment by looppi** [comment]
The biggest difference is how electronic material is referenced. Previous version included [online] and [viitattu 13.3.2014] entries and the current version is as follows:

```
Gartner. (2010). Cloud services brokerage: Taking intermediation to the next level. Haettu 1.11.2011 osoitteesta http://www.gartner.com/it/content/1461800/1461813/december_2_cloud_services_brokerage_blheureux.pdf
```

**Comment by datakurre** [comment]
Ok. Seems that the old information is enough, so probably you are able to just search an replace the required changes in tutkielma.bst :)

**Comment by looppi** [comment]
Noticed that also the formatting in the references of proceedings in books has changed, I'll create another pull request for it.
