### ISSUE TITLE
Unable to change language into English

### ISSUE THREAD

**Issue by Cykyter** [datakurre/tutkielma#7]
There is no support for gradu2 style switching of thesis language into English (eg. (\documentclass[english]{tutkielma}).

Changing language definitions in tutkielma.cls is not enough for language conversion as citation language also needs to be changed (tutkielma.bst).

**Comment by datakurre** [comment]
@Cykyter I'm afraid that this is by design to keep the style somewhat manageable.

Yet, if the problem is only about citations, you can simply copy ``tutkielma.bst``, translate it and use it with ``\def\mybibliographystyle{tutkielma.en.bst}``.

**Comment by datakurre** [comment]
@Cykyter Have you been able to translate tutkielma.bst into English (e.g. tutkielma.en.bst)? If you could provide translated version of the bst, we could probably add a language based condition into cls to select it instead of the default Finnish one.

**Comment by Cykyter** [comment]
@datakurre  I've manually translated the "language-specific" section in the tutkielma.bst into English and that seemed to be enough. However this probably wasn't the correct way of translating the file?

Gist of the translated file: https://gist.github.com/Cykyter/b171a0af1a7329042387

**Comment by datakurre** [comment]
@Cykyter Thanks. I'll look into merging that later.
